//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hangman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap body {
            get {
                object obj = ResourceManager.GetObject("body", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream correctanswer {
            get {
                return ResourceManager.GetStream("correctanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///  &lt;Word&gt;kamion&lt;/Word&gt;
        ///  &lt;Word&gt;video&lt;/Word&gt;
        ///  &lt;Word&gt;tablet&lt;/Word&gt;
        ///  &lt;Word&gt;ljubov&lt;/Word&gt;
        ///  &lt;Word&gt;jorgan&lt;/Word&gt;
        ///  &lt;Word&gt;momce&lt;/Word&gt;
        ///  &lt;Word&gt;zgrada&lt;/Word&gt;
        ///  &lt;Word&gt;tepih&lt;/Word&gt;
        ///  &lt;Word&gt;zivot&lt;/Word&gt;
        ///  &lt;Word&gt;srekja&lt;/Word&gt;
        ///  &lt;Word&gt;sokak&lt;/Word&gt;
        ///  &lt;Word&gt;student&lt;/Word&gt;
        ///  &lt;Word&gt;dozd&lt;/Word&gt;
        ///  &lt;Word&gt;hemija&lt;/Word&gt;
        ///  &lt;Word&gt;ajvar&lt;/Word&gt;
        ///  &lt;Word&gt;pracka&lt;/Word&gt;
        ///  &lt;Word&gt;avokado&lt;/Word&gt;
        ///  &lt;Word&gt;armija&lt;/Word&gt;
        ///  &lt;Word&gt;astibo&lt;/Word&gt;
        ///  &lt;Word&gt;zamok&lt;/Word&gt;
        ///  &lt;Word&gt;karpa&lt;/Word&gt;
        ///  &lt;Word&gt;zmija&lt;/Word&gt;
        ///  &lt;Wor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hanged {
            get {
                object obj = ResourceManager.GetObject("hanged", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Word&gt;
        ///	&lt;Word&gt;telepatija&lt;/Word&gt;
        ///	&lt;Word&gt;avtokefalnost&lt;/Word&gt;
        ///	&lt;Word&gt;modernizacija&lt;/Word&gt;
        ///	&lt;Word&gt;helikobakterija&lt;/Word&gt;
        ///	&lt;Word&gt;energetika&lt;/Word&gt;
        ///	&lt;Word&gt;burebarut&lt;/Word&gt;
        ///	&lt;Word&gt;hidrometeorologija&lt;/Word&gt;
        ///	&lt;Word&gt;seizmologija&lt;/Word&gt;
        ///	&lt;Word&gt;svetagora&lt;/Word&gt;
        ///	&lt;Word&gt;kajmakcalan&lt;/Word&gt;
        ///	&lt;Word&gt;solunskaglava&lt;/Word&gt;
        ///	&lt;Word&gt;programiranje&lt;/Word&gt;
        ///	&lt;Word&gt;industrija&lt;/Word&gt;
        ///	&lt;Word&gt;nacionalnost&lt;/Word&gt;
        ///	&lt;Word&gt;kanalizacija&lt;/Word&gt;
        ///	&lt;Word&gt;kapitalizam&lt;/Word&gt;
        ///	&lt;Word&gt;istrazuvanje&lt;/Word&gt;
        ///	&lt;Word&gt;civilizacija&lt;/Word&gt;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap head {
            get {
                object obj = ResourceManager.GetObject("head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Land_008 {
            get {
                object obj = ResourceManager.GetObject("Land_008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_hand {
            get {
                object obj = ResourceManager.GetObject("left_hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap left_leg {
            get {
                object obj = ResourceManager.GetObject("left_leg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream MainTheme {
            get {
                return ResourceManager.GetStream("MainTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Words&gt;
        ///	&lt;Word&gt;prikolka&lt;/Word&gt;
        ///	&lt;Word&gt;lubenica&lt;/Word&gt;
        ///	&lt;Word&gt;avtomobil&lt;/Word&gt;
        ///	&lt;Word&gt;kompjuter&lt;/Word&gt;
        ///	&lt;Word&gt;devojka&lt;/Word&gt;
        ///	&lt;Word&gt;telefon&lt;/Word&gt;
        ///	&lt;Word&gt;baterija&lt;/Word&gt;
        ///	&lt;Word&gt;fakultet&lt;/Word&gt;
        ///	&lt;Word&gt;patuvanje&lt;/Word&gt;
        ///	&lt;Word&gt;letuvanje&lt;/Word&gt;
        ///	&lt;Word&gt;geografija&lt;/Word&gt;
        ///	&lt;Word&gt;inzenerstvo&lt;/Word&gt;
        ///	&lt;Word&gt;havarija&lt;/Word&gt;
        ///	&lt;Word&gt;lihnidos&lt;/Word&gt;
        ///	&lt;Word&gt;republika&lt;/Word&gt;
        ///	&lt;Word&gt;manastir&lt;/Word&gt;
        ///	&lt;Word&gt;zemjotres&lt;/Word&gt;
        ///	&lt;Word&gt;jakupica&lt;/Word&gt;
        ///	&lt;Word&gt;divakoza&lt;/Word&gt;
        ///	&lt;Word&gt;jamajka&lt;/Word&gt;
        ///	&lt;Word&gt;golemina [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_hand {
            get {
                object obj = ResourceManager.GetObject("right_hand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sidepanel {
            get {
                object obj = ResourceManager.GetObject("sidepanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream wronganswer {
            get {
                return ResourceManager.GetStream("wronganswer", resourceCulture);
            }
        }
    }
}
